packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

publicHoistPattern:
  - '@typescript/native'
  - typescript
  - typegraphql-prisma
